openapi: 3.1.0
info:
  title: Gestor de Gastos API
  description: API para leer y escribir gastos financieros en Google Sheets.
  version: 1.0.0
servers:
  - url: https://custom-gpt-sheets-action.vercel.app
    description: Dominio del plugin (requerido por OpenAI)
paths:
  /v4/spreadsheets/{spreadsheetId}/values/{range}:
    get:
      operationId: getSheetData
      summary: Leer valores de una hoja de cálculo
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos de la hoja
          content:
            application/json:
              schema:
                type: object
    post:  # ✅ este reemplaza "append:"
      operationId: appendSheetData
      summary: Agregar una fila a una hoja de cálculo
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        '200':
          description: Fila agregada exitosamente
          content:
            application/json:
              schema:
                type: object