openapi: 3.1.0
info:
  title: Gestor de Gastos API
  description: API para leer y escribir gastos financieros en Google Sheets.
  version: 1.0.0
servers:
  - url: https://custom-gpt-sheets-action.vercel.app
    description: Dominio base para las acciones del plugin
paths:
  /sheets/{spreadsheetId}/read/{range}:
    get:
      operationId: getSheetData
      summary: Leer datos desde una hoja de cálculo
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos leídos exitosamente
          content:
            application/json:
              schema:
                type: object
  /sheets/{spreadsheetId}/append/{range}:
    post:
      operationId: appendSheetData
      summary: Agregar una fila a una hoja de cálculo
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        '200':
          description: Fila agregada exitosamente
          content:
            application/json:
              schema:
                type: object
