openapi: 3.1.0
info:
  title: API de Carga de Gastos
  description: Inserta datos en una hoja de cálculo de Google Sheets.
  version: 1.0.0
servers:
  - url: https://script.google.com/macros/s/AKfycbyEuqXXtR3TEOmgPUTl--peyDZJ_KlIc16YOim-Y0cHbGH3OxKl8_AOU1MWs57MHVqv/exec
    description: Web App pública para Google Sheets

paths:
  /:
    post:
      operationId: appendExpense
      summary: Agregar un gasto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        '200':
          description: Confirmación de éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
